/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SagessesRouteImport } from './routes/sagesses'
import { Route as IndexRouteImport } from './routes/index'

const SagessesRoute = SagessesRouteImport.update({
  id: '/sagesses',
  path: '/sagesses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sagesses': typeof SagessesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sagesses': typeof SagessesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sagesses': typeof SagessesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sagesses'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sagesses'
  id: '__root__' | '/' | '/sagesses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SagessesRoute: typeof SagessesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sagesses': {
      id: '/sagesses'
      path: '/sagesses'
      fullPath: '/sagesses'
      preLoaderRoute: typeof SagessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SagessesRoute: SagessesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
